version: "3.9"

services:
  qflood:
    image: jesec/flood
    command:
      - --port 3000
      - --allowedpath /data
      - --auth=none
      - --trurl=http://192.168.0.202:8080/transmission/rpc
      - --truser=
      - --trpass=
    volumes:
      - ./qflood/config:/config
      - ./qflood/data:/data
    ports:
      - 3000:3000
    restart: unless-stopped
    network_mode: "bridge"

  wireguard:
    image: weejewel/wg-easy:latest
    network_mode: "bridge"
    cap_add:
      - net_admin
      - sys_module
    ports:
      - "53217:51820/udp"
      - "8082:51821/tcp"
    volumes:
      - ./wg-easy:/etc/wireguard
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    environment:
      WG_HOST: "${PUBLICIP}"
      PASSWORD: "${PASSWORD}"

  ovpn:
    image: alekslitvinenk/openvpn:latest
    cap_add:
      - net_admin
    network_mode: "bridge"
    volumes:
      - ./ovpn:/opt/Dockovpn_data
    ports:
      - "53211:1194/udp"
      - "8081:8080/tcp"
    restart: unless-stopped

  web:
    image: halverneus/static-file-server:latest
    volumes:
      - ./shared:/web
    network_mode: "bridge"
    ports:
      - "8080:8080"
    restart: unless-stopped

  https-portal:
    image: steveltn/https-portal:1
    network_mode: "bridge"
    environment:
      STAGE: 'production'
      DOMAINS: 'hesamian.myddns.me'
    ports:
    - '80:80'
    - '443:443'
    volumes:
      - ./shared:/var/www/vhosts/hesamian.myddns.me
      - /data/ssl_certs:/var/lib/https-portal

  samba:
    image: dperson/samba
    restart: unless-stopped
    stdin_open: true
    tty: true
    network_mode: "bridge"
    environment:
      # advertise shares, default: true, or false (open ports 137, 138)
      NMBD: "true"
      USER: "${USERNAME};${PASSWORD}"
      USERID: 1000
      GROUPID: 1000
      SHARE: "shared;/shares/shared;yes;no;yes;all;none;;dell-server"
      WORKGROUP: "WORKGROUP"
      RECYCLE: ""
    ports:
      - "137:137/udp" # required to advertise shares (NMBD)
      - "138:138/udp" # required to advertise shares (NMBD)
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
    read_only: false
    volumes:
      - ./shared:/shares/shared
    cap_add:
      - net_admin
